feat: Adds Docker Push input parameter for extra docker tags
entur/gha-docker pull request #129
Opened 2024-09-30 12:24 UTC by hw-knowit

Docker Push now accepts a comma-separated list of extra tags to be pushed to registry.

2024-09-30 14:05 UTC, bvestli commented
We need to make tests for this feature. I can have a look at it.

2024-10-01 07:53 UTC, Glenn-Terjesen commented on .github/workflows/push.yml
> +          echo $tags | while read -d ',' -r tag || [[ -n $tag ]]; do
```suggestion
          echo "$tags" | while read -d ',' -r tag || [[ -n $tag ]]; do
```

2024-10-01 07:53 UTC, Glenn-Terjesen commented on .github/workflows/push.yml
> +            docker push $remote_tag
```suggestion
            docker tag "$local_tag" "$remote_tag"
            docker push "$remote_tag"
```

2024-10-01 07:55 UTC, Glenn-Terjesen commented on .github/workflows/push.yml
> +        description: "EXPERIMENTAL: Extra Docker tags to apply and push, comma separated. Requires project-level setting 'Execute Triggers With All Collected Artifacts or Manifests' in Harness."
```suggestion
        description: "Extra Docker tags to apply and push (comma separated)- Requires Harness project-level setting 'Execute Triggers With All Collected Artifacts or Manifests'"
```

2024-10-01 08:53 UTC, Glenn-Terjesen requested changes
Litt fikser så ser det bra ut!

2024-10-01 10:33 UTC, hw-knowit commented
Ser ut som workflows her ikke takler forks 😅

2024-10-04 13:43 UTC, hw-knowit commented
Superseded by #136.

2024-10-04 13:43 UTC, closed without merging